# Generated by Django 3.2.9 on 2021-12-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_auto_20211201_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydetails',
            options={'verbose_name_plural': 'Company Details'},
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='company_name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
