# Generated by Django 3.2.9 on 2022-01-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_auto_20220117_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
