# Generated by Django 3.2.9 on 2022-01-12 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='company_details',
        ),
    ]
