# Generated by Django 3.2.9 on 2021-11-14 19:44

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.TextField()),
                ('slogan', models.TextField()),
                ('what_company_does', models.TextField()),
                ('colours', models.TextField()),
                ('look_feel', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(editable=False, max_length=264, verbose_name=orders.models.Order)),
                ('slogan', models.CharField(editable=False, max_length=264, verbose_name=orders.models.Order)),
                ('what_company_does', models.CharField(editable=False, max_length=600, verbose_name=orders.models.Order)),
                ('colours', models.CharField(editable=False, max_length=264, verbose_name=orders.models.Order)),
                ('look_feel', models.CharField(editable=False, max_length=264, verbose_name=orders.models.Order)),
                ('price_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='orders.order')),
            ],
        ),
    ]
