# Generated by Django 3.2.9 on 2021-11-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6),
            preserve_default=False,
        ),
    ]
